### ISSUE TITLE
Idea: DeepStateContainer to mimic 0.4 api?

### ISSUE THREAD

**Issue by cambiata** [ciscoheat/deepstate#16]
Just and idea: 

As deepstate isn't a container anymore (rather an instance of the state itself), it maybe could be convenient to include something like a DeepStateContainer in the library? Apart from carrying the asset instance, it could setup a default observable... Actually, mimic the pre 0.4 container api...? :-)

**Comment by ciscoheat** [comment]
I created `ObservableDeepState` because of that, it's described in the docs: https://github.com/ciscoheat/deepstate#observable

**Comment by cambiata** [comment]
Ah, great! But, still I have to wrap the asset into a container to keep track of the updates, don't I? Not really a problem - below is a minimalistic container and view example as I would implement it.

Everything works fine, except that I miss the boolean Immediate evaluation flag in the 0.4 release.
(Now I can invoke the listener by providing a *new* state object, but that's not what I want. I want to be able to fetch the current state...)

```
class Main {
	static function main() {
		var container = new Container({
			age: 11,
			name: 'Bob',
		});
		var ageView = new AgeView(container);
		container.setAge(22);
		container.setAge(33);
	}
}

typedef State = {
	final age:Int;
	final name:String;
}

class ObservableAsset extends DeepState.ObservableDeepState<ObservableAsset, State> {}

class Container {
	public function new(init:State)
		this.asset = new ObservableAsset(init);

	public var asset(default, null):ObservableAsset;

	public function setAge(v:Int)
		this.asset = asset.update(this.asset.state.age, v);
}

class AgeView {
	public function new(container:Container) {
		container.asset.observable.subscribe(container.asset.state.age, age -> {
			this.age = age;
			this.render();
		});
	}

	var age:Int;

	function render() {
		trace('AgeView.render(): Current age is $age');
	}
}

```

**Comment by ciscoheat** [comment]
The point is to have DeepState guaranteed controlled (immutable), that's why I removed the mutable state var from the API, it was a mistake to add it initially because you can never make any guarantees about it. 

When mutable, any part of the program can change it, which is back to hypergalactic GOTOs. For game frameworks it works very well since they operate on a game loop, like how it's done in SnakeDCI: https://github.com/ciscoheat/SnakeDCI/blob/immutable-asset/src/GameView.hx#L167-L170

The current trend of web frameworks uses a mutable store instead, and of course each framework differs a bit in every trendy implementation of the current trend, and the next trend seems to go towards observables. I will think about how to please the followers of the current and the upcoming trend in a good enough way.

BTW, what's the problem with invoking the listener with the current state:

```haxe
public function new(container:Container) {
	container.asset.observable.subscribe(container.asset.state.age, age -> {
		this.age = age;
		this.render();
	}, container.asset.state);
}
```

**Comment by cambiata** [comment]
> BTW, what's the problem with invoking the listener with the current state:

Ah, I just didin't expect that to invoke the callback, because there wouldn't be any actual state change... 
Thank you for your great work! 👍

**Comment by ciscoheat** [comment]
There's a `DeepStateContainer` available now for all mutable needs, check the docs.

**Comment by cambiata** [comment]
Great! Thanx!
