### ISSUE TITLE
Async handling?

### ISSUE THREAD

**Issue by cambiata** [ciscoheat/deepstate#2]
We all deal with async nowadays, so some example/suggestion of how to handle this in deepstate would be fine. 

(I guess that due to the fact that deepstate doesn't really depend on "actions", async handling is architecturally not really a "deepstate matter"..?)

**Comment by ciscoheat** [comment]
> (I guess that due to the fact that deepstate doesn't really depend on "actions", async handling is architecturally not really a "deepstate matter"..?)

I'm leaning towards that too, also because the library is cross-platform. For now I think the async part of the action has to handle it, and when all data has been gathered, call `updateIn`.

Since there is no requirement to return anything specific from the action methods specified in the class inheriting from  `DeepState<T>`, they could be made async as wanted, by returning a Promise for example.

**Comment by cambiata** [comment]
Fair enough! 
BTW, have you had time to play with DenkiYagi's crossplatform Promise library? https://github.com/DenkiYagi/hxgnd/blob/master/src/hxgnd/Promise.hx

**Comment by ciscoheat** [comment]
I haven't, but will check it out! Looks nice, especially with the native js compatibility.
