### ISSUE TITLE
Storing non-rigid objects, e.g css style object?

### ISSUE THREAD

**Issue by cambiata** [ciscoheat/deepstate#6]
Any plans for a way to store non-rigid objects, for example a css style object?

**Comment by ciscoheat** [comment]
You mean with non-rigid objects, those that can mutate its state?

**Comment by cambiata** [comment]
No, just Dynamic. Let's say that you want to store css styling info. Could be an object with any combination of style properties.

**Comment by ciscoheat** [comment]
If it's Dynamic, it could easily mutate and go against the point of this project, which is that you shouldn't be able to change anything in the state tree, only create a new one with the updated data. 

I thought about using `Any` for this, which could be a possibility since you then must cast it to something else and thereby "state your intention". But a better way for Dynamic data could be to make an ImmutableDynamicAccess abstract type. That shouldn't be much of a problem!

**Comment by ciscoheat** [comment]
I'm experimenting with an `ImmutableJson` type now. Use array access for nested structure access, and `get` for value access.
