### ISSUE TITLE
Asset as property bug/feature?

### ISSUE THREAD

**Issue by cambiata** [ciscoheat/deepstate#9]
Hi Andreas!

Noticed something strange when playing around. With the following setup...
```
typedef State = {
	final score:Int;
}

class Asset extends DeepState<State> {
	 public function new(initialState, middlewares=null) super(initialState, middlewares);
}
```
...everything works as expected when instantiating the asset as a local variable:
```
class Main {
	static function main() new Main();
	public function new() {
		var asset = new Asset({score:444}); // <--- Local variable
		asset.updateIn(asset.state.score , score->score+1); // Works fine!
		trace(asset.state.score);
	}
}
```
However, if I instantiate the asset as a property field of Main, I get "uncaught exception: Error: Field not found in state: asset.state.score":
```
class Main {
	static function main() new Main();
	var asset:Asset; // <------------
	public function new() {
		asset = new Asset({score:444}); <--- Class property
		asset.updateIn(asset.state.score , score->score+1); // Error: Field not found...
		trace(asset.state.score);
	}
}
```
Is this expected?

**Comment by ciscoheat** [comment]
This is a limitation right now, as a quick way to ensure type safety. The recommended way to use the update methods is to only call them from within the `Asset` class that inherits from `DeepState<T>`. 

From there you only need to use `state.score` instead of `localVar.state.score`, fixing the problem for the moment. I'll soon enforce that unless using a compiler define, as described in #8. But the problem with local vars will be fixed in #7, which is next on the list!

**Comment by cambiata** [comment]
Cool! Thanks for clarifying!

**Comment by ciscoheat** [comment]
This should be fixed now, by simply disallowing any field named "state" in the state structure.
